// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package homeassistant

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/pedromol/camelo/pkg/homeassistant/HomeAssistant",
		Iface: reflect.TypeOf((*HomeAssistant)(nil)).Elem(),
		Impl:  reflect.TypeOf(HASS{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return homeAssistant_local_stub{impl: impl.(HomeAssistant), tracer: tracer, initMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/pedromol/camelo/pkg/homeassistant/HomeAssistant", Method: "Init", Remote: false}), toggleMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/pedromol/camelo/pkg/homeassistant/HomeAssistant", Method: "Toggle", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return homeAssistant_client_stub{stub: stub, initMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/pedromol/camelo/pkg/homeassistant/HomeAssistant", Method: "Init", Remote: true}), toggleMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/pedromol/camelo/pkg/homeassistant/HomeAssistant", Method: "Toggle", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return homeAssistant_server_stub{impl: impl.(HomeAssistant), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return homeAssistant_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[HomeAssistant] = (*HASS)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*HASS)(nil)

// Local stub implementations.

type homeAssistant_local_stub struct {
	impl          HomeAssistant
	tracer        trace.Tracer
	initMetrics   *codegen.MethodMetrics
	toggleMetrics *codegen.MethodMetrics
}

// Check that homeAssistant_local_stub implements the HomeAssistant interface.
var _ HomeAssistant = (*homeAssistant_local_stub)(nil)

func (s homeAssistant_local_stub) Init(ctx context.Context) (err error) {
	// Update metrics.
	begin := s.initMetrics.Begin()
	defer func() { s.initMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "homeassistant.HomeAssistant.Init", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Init(ctx)
}

func (s homeAssistant_local_stub) Toggle(ctx context.Context, a0 string) (err error) {
	// Update metrics.
	begin := s.toggleMetrics.Begin()
	defer func() { s.toggleMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "homeassistant.HomeAssistant.Toggle", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Toggle(ctx, a0)
}

// Client stub implementations.

type homeAssistant_client_stub struct {
	stub          codegen.Stub
	initMetrics   *codegen.MethodMetrics
	toggleMetrics *codegen.MethodMetrics
}

// Check that homeAssistant_client_stub implements the HomeAssistant interface.
var _ HomeAssistant = (*homeAssistant_client_stub)(nil)

func (s homeAssistant_client_stub) Init(ctx context.Context) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.initMetrics.Begin()
	defer func() { s.initMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "homeassistant.HomeAssistant.Init", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 0, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s homeAssistant_client_stub) Toggle(ctx context.Context, a0 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.toggleMetrics.Begin()
	defer func() { s.toggleMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "homeassistant.HomeAssistant.Toggle", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.23.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type homeAssistant_server_stub struct {
	impl    HomeAssistant
	addLoad func(key uint64, load float64)
}

// Check that homeAssistant_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*homeAssistant_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s homeAssistant_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Init":
		return s.init
	case "Toggle":
		return s.toggle
	default:
		return nil
	}
}

func (s homeAssistant_server_stub) init(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Init(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s homeAssistant_server_stub) toggle(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Toggle(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type homeAssistant_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that homeAssistant_reflect_stub implements the HomeAssistant interface.
var _ HomeAssistant = (*homeAssistant_reflect_stub)(nil)

func (s homeAssistant_reflect_stub) Init(ctx context.Context) (err error) {
	err = s.caller("Init", ctx, []any{}, []any{})
	return
}

func (s homeAssistant_reflect_stub) Toggle(ctx context.Context, a0 string) (err error) {
	err = s.caller("Toggle", ctx, []any{a0}, []any{})
	return
}
